spring.application.name=oracle-java-bot-backend

server.port=8080

# ========================
# ORACLE DATABASE (WALLET)
# ========================
spring.datasource.url=jdbc:oracle:thin:@adbps_medium?TNS_ADMIN=wallet
spring.datasource.username=DEV
spring.datasource.password=Pass2026****
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================
# LIQUIBASE (disable if not using)
# ========================
spring.liquibase.enabled=false

# ========================
# CORS (for frontend)
# ========================
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# ========================
# LOGGING
# ========================
logging.level.root=INFO
logging.file.name=logs.log
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ========================
# TELEGRAM BOT
# ========================
telegram.bot.enabled=true
telegram.bot.token=8605069154:AAFtlFIC1uplWqfxp6cNd5fPpaCX-CdAtj8
telegram.bot.name=botnuevo25022026_bot

# ========================
# EXTERNAL API
# ========================
deepseek.api.key=sk-test
deepseek.api.url=https://api.deepseek.com/v1/chat/completions