@startuml
title com.springboot.MyTodoList.controller - generated class diagram

class AIPriorityController
class AnalyticController
class ProjectController
class SprintController
class TaskLogController
class TeamController
class UserController

@enduml
