@startuml
title com.springboot.MyTodoList.service - generated class diagram

class AnalyticService
class ProjectService
class SprintService
class TaskLogService
class TaskService
class TeamService
class UserService

@enduml
